from docx import Document

document = Document()
document.add_heading('John Doe', 0)
document.add_paragraph('john.doe@example.com | 123-456-7890 | linkedin.com/in/johndoe | github.com/johndoe')
document.add_heading('Software Engineer', level=1)
document.add_paragraph('Passionate software engineer with 5 years of experience in Python and JavaScript.')
document.add_heading('Experience', level=1)
document.add_paragraph('Software Engineer at Tech Corp (Jan 2020 - Present)')
document.add_paragraph('• Developed scalable microservices using Python and Flask.')
document.add_paragraph('• Implemented frontend features using React and Redux.')
document.add_paragraph('• Increased system performance by 20% through code optimization.')
document.add_heading('Education', level=1)
document.add_paragraph('B.S. in Computer Science, University of Technology (2015-2019)')
document.add_heading('Skills', level=1)
document.add_paragraph('Python, JavaScript, React, Node.js, Docker, Kubernetes, SQL, AWS, Git')
document.add_heading('Projects', level=1)
document.add_paragraph('AI Analyzer: Built an AI tool that improved efficiency by 30%.')
document.save('test_resume.docx')
print("Dummy resume created at test_resume.docx")
